### ISSUE TITLE
Dropped Neos 4.3 support

### ISSUE THREAD

**Issue by Sebobo** [KaufmannDigital/KaufmannDigital.GDPR.CookieConsent#27]
I still have the version 3.0.1 running perfectly fine in a Neos 4.3 project.

Is there any reason the newer releases don't support it anymore?
4.3 still runs until 2022.

If there is a compatibility issue I can probably help fixing it.

**Comment by Nikdro** [comment]
Hi @Sebobo!

First of all, sorry for the late response. Unfortunately, these old tickets from the package have been a little forgotten by us and are only now being reviewed. Sorry for that!

Is this topic still relevant for you? We are not doing active maintenence on Version 3.X today. I'm also not sure, what was the exact reason there. There was one, but nothing which would be an abolute show-stopper.  
If you are using an old version of our banner until now, please re-open this issue and let us know which versions you would like to use with with Neos-Versions. Then I'll have a look what to do here. 

But I would strongly recommend to use the latest version of our package here, because so much changed and many features came with 4 and 5. Also upgrading isn't hard. Let me know, if you need some assistance. 

If the old logging-feature (which was droped later) keeps you away from updating, please also let me know. We where already thinking of a new logging feature with much more infos in it for the newest version. We had to drop support for the old feature, because multi-site/multi-dimension/etc made it too complicated for the old logging-setup. 

Greetings 
Niklas

**Comment by Sebobo** [comment]
It's a bit of a problem if composer requirements change in a patch release (3.0.2) and a version is then unsupported suddenly even though more patches arrive later. 
At least a minor release for dependency changes would be better.

But this is not an issue anymore as I forked it and its unclear if the project will be further developed/updated.

**Comment by Nikdro** [comment]
Thanks for your Feedback @Sebobo! 
Yes, I totally agree with you that a minor release would have been the cleaner way to go here. 

Still, thanks for your feedback and the feedback. Nice to here, that your problem is solved 🙂
